server:
  port: 8083

spring:
  application:
    name: application-service

  datasource:
    url: jdbc:mysql://localhost:3306/application_db
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect   

  rabbitmq:
    host: localhost
    port: 5672

# ✅ EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# ✅ ACTUATOR + TRACING
management:
  endpoints:
    web:
      exposure:
        include: health,info

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
